sudo: required
dist: bionic
addons:
  snaps:
    - name: juju
      confinement: classic
    - lxd
language: python
install: pip install tox-travis
matrix:
  include:
    - python: 3.6
      env: ENV=lint-light
    - python: 3.8
      env: ENV=lint-light
    - env: ENV=lint
comment: |
  install dependencies in script phase saving time on simpler test environments
  change permissions on lxd socket to allow travis user access
  (^^ this is a throw-away CI environment, do not do this at home)
script:
  - if [ $ENV = 'lint' ]; then
      sudo apt remove -y --purge lxd lxd-client;
      sudo lxd waitready;
      sudo lxd init --auto;
      sudo chmod 666 /var/snap/lxd/common/lxd/unix.socket;
      juju bootstrap --no-gui localhost;
    fi
  - tox -e $ENV
